language: php
sudo: required
services:
- docker
notifications:
    slack:
        - watzekdi:zEtuD1WHpN9DYmzZFzTsfudX#general
    webhooks:
        urls:
            - https://hooks.microbadger.com/images/watzek/omeka/uIJofxFmDjreMKXsfY3XM7ZGiCw=
env:
  global:
  - secure: hspQFTVMEXBVg28D1VdZ6MKnt/Ow4ICxr1ogeJuBIP4WvC+c/JdTnI5+ILWCQ2KYTUynA+EL8+MdZKHDMwkfmJYkbb2IjxnB5x4C8Jp781x3ZSy9Td3mWBAlHZPJSO9htI4Se2RNsotlit/b+16LOY2xwyHjxtn+AyxOWyWNqUqyhICn6AcgMTP+iv6LyqEqTxR6uXikFo7P8h+yKcaBCDcLcrA8jO5ZiaAiPmP/abK9MbQ52NXvs+ZRKg2g+lL/db1dlFaQiQRyqnWT5wAsR7AFr/W+EJz7y3i+KtYj/2g2PxCIE0rymKGlAuN12hbMDnReuQh55Q1xjhvUUP12dbs5KMJQ1EMR5VC1Bpy6ZQDRh71fQq0yfmCPnUBdtBSsRVk3rzfC/0qrnd62TTluLXzAgS+nVWdeaBr/unzhK2D8QwiwyKwneDRkidlwSSXYGZbqsbXxDsnSFjuwJix7JBtWvrSKDmQ/fiM5lAnKOxyr8j/xOUcqex3qNZlajOef//lnxfuqikXvNnPw2ZZFZ35Veuun+aqCKZoVvkDfmIgCfD9Qb5u8zekf+bL1/WGcASRrL+zJ7lSRD20NLwpsT6ZWAI3YxgQ98CFZoxfYlMUOFn2d6D1eFTu/GoLQIuu+RjcahOZrdIkVWruzrXzuMmJ8rLnMUxNIQHYQ1ogvmEM=
  - secure: R3XALzT59k3HoT+t+BQi+j0wWWh4JCVq1A2gCkeJHzhWFuAaE9AWCE0ZfpO92ZWsQ4qu1JD9rBnFrvjNRrGLW/UqXp82S7c2T89LlDgPjBOS3pfZv6EOzkjvBEcGEiJHyoYxwv+iLPvxiMslFPBMHOH5+h+jgwvCA8oekggFVlDGe5zqpBKSKeLGQs/p5Y7hhc66r38WxC2ztAN1aF6jNRLRmdr3ljJ0ycWPn1i0ogYVn4i/qynqI2iwGurXZM3S1Quk1hu9WmY2cUFo7RBcVIXghOWbxWRH7B7UXCesVa6LWvudNwz4nrhQssyn2VpEf5Mo/8XdaohwnwBeTu2hi/KxcinAz/yMS/G9JdkvZvZVyUTZVqYza5Iw6vp7hHwKLx+Lr6+gzYFvqU9fQnrXhE0nzkFXmjm77q1VTa6nManhT5EqxGagst/srtZycGYXyaF6T5aOKJDbW+AV3nGWZviQxXgkD/XOpqmCwRysogmONnXbK/NU8cTJT5HOiMajqzhi7v7rMhN0HPggEnbU2z2Fkx8lKMhq7PSdOJXcbS5QN3UZ7b+V1kfOkj8/19fgqmrEIHYssukYWoDI7Sfi5+zczAaWUSgZo9uctcBgosPu4weBxM0socGveuJYSpm3oBUrEo3lreZc0OfyivUb+myo/VkQVyygZiP+zm/wnbY=
script:
- ./build.sh && ./push.sh
