version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on: 
      - db
    ports: 
      - 8081:80

  omeka:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      OMEKA_DB_HOST: db:3306
      OMEKA_DB_USER: omeka
      OMEKA_DB_PASSWORD: omeka
      OMEKA_DB_NAME: omeka
      OMEKA_DB_PREFIX: _omeka
      OMEKA_DB_CHARSET: utf8
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
      APPLICATION_ENV: production
    volumes: 
      - www:/var/www/Omeka

volumes: 
  www:
